### PR TITLE
Automatic build & CI

### PR DESCRIPTION
**Pull request by ya1gaurav**
This is initial file for travis automatic build & continuous integration in liboauth.

### CODE REVIEW

**Comment by ya1gaurav** [comment]
@Robin , could you open https://travis-ci.org/ (github login will work) , it will show all projects in your repositories. There just switch on travis automatoc build. I did it for my own fork, it works.

**Comment by ya1gaurav** [comment]
Are you able to watch: https://travis-ci.org/ya1gaurav/liboauth/jobs/80871417  ??

**Comment by x42** [comment]
works. thanks a lot!

**Comment by ya1gaurav** [comment]
are there some open items in liboauth? or is it complete & stable?

**Comment by x42** [comment]
It is stable and pretty much complete.

There are a few things that would be nice to have (grep the source for `TODO`), but it's really all minor and there is little interest since most services have switched to OAuth2 (which is purely flow-based and does not need a lib).

**Comment by ya1gaurav** [comment]
OAuth2 is also maintained by you ? is it on github ?

**Comment by x42** [comment]
No, I don't. See http://oauth.net/2/ for a list of OAuth2 implementations.

**Pull request merged**
